export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";


export const USER_REGISTER_REQUEST="USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS="USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL="USER_REGISTER_FAIL";

export const LOAD_USER_REQUEST="LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS="LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL="LOAD_USER_FAIL";


export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAIL="LOGOUT_FAIL";


export const UPDATE_PROFILE_REQUEST="UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS="UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_REST="UPDATE_PROFILE_REST";
export const UPDATE_PROFILE_FAIL="UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD_REQUEST="UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS="UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_REST="UPDATE_PASSWORD_REST";
export const UPDATE_PASSWORD_FAIL="UPDATE_PASSWORD_FAIL";



export const FORGOT_PASSWORD_REQUEST="FORGOT_PASSWORD_REQUEST";
export const FROGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_REST="FORGOT_PASSWORD_REST";
export const FORGOT_PASSWORD_FAIL="FORGOT_PASSWORD_FAIL";


export const RESET_PASSWORD_REQUEST="RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_REST="RESET_PASSWORD_REST";
export const RESET_PASSWORD_FAIL="RESET_PASSWORD_FAIL";


// Admin


export const ALL_USERS_REQUEST="ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS="ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL="ALL_USERS_FAIL";



export const USER_DETAILS_REQUEST="USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS="USER_DETAILS_SUCCESS";
export const USER_DETAILS_REST="USER_DETAILS_REST";
export const USER_DETAILS_FAIL="USER_DETAILS_FAIL";


export const USER_UPDATED_REQUEST="USER_UPDATED_REQUEST";
export const USER_UPDATED_SUCCESS="USER_UPDATED_SUCCESS";
export const USER_UPDATED_REST="USER_UPDATED_REST";
export const USER_UPDATED_FAIL="USER_UPDATED_FAIL"

export const USER_DELETE_REQUEST="USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS="USER_DELETE_SUCCESS";
export const USER_DELETE_REST="USER_DELETE_REST";
export const USER_DELETE_FAIL="USER_DELETE_FAIL"


export const CLEAR_ERRORS="CLEAR_ERRORS";